{% set name = "hoomd" %}
{% set tag_version = "3.0.0-beta.12" %}
{% set conda_version = "3.0.0dev12" %}
{% set build = 0 %}
{% set sha256 = "f2aead735abc4dd46b4bb69198a66bbcfe7016675b4a4e227958074ff7e7e34b" %}
{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
{% set processor = "cpu" %}  # [not linux64]


package:
  name: {{ name }}
  version: "{{ conda_version }}"

source:
  fn: {{ name }}-{{ tag_version }}.tar.gz
  url: https://github.com/glotzerlab/hoomd-blue/releases/download/v{{ tag_version }}/{{ name }}-v{{ tag_version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  # Upstream package does not support Windows, Python < 3.6, or PyPy
  skip: true  # [win or py<36 or python_impl == "pypy"]
  string: "{{ processor }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  script: "bash ${RECIPE_DIR}/build_hoomd.sh gpu"  # [linux64 and cuda_compiler_version != "None"]
  script: "bash ${RECIPE_DIR}/build_hoomd.sh"  # [not linux64 or cuda_compiler_version == "None"]

  rpaths:
    - lib/
    - lib/python3.10/site-packages/{{ name }}  # [py==310]
    - lib/python3.9/site-packages/{{ name }}  # [py==39]
    - lib/python3.8/site-packages/{{ name }}  # [py==38]
    - lib/python3.7/site-packages/{{ name }}  # [py==37]
    - lib/python3.6/site-packages/{{ name }}  # [py==36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    # MacOS cross compilation support requires CMake 3.15 or newer
    - cmake >=3.16.0
    - ninja
    - pkg-config

  host:
    - eigen
    - numpy
    - pybind11
    - python
    - tbb
    - tbb-devel

  run:
    - __cuda >={{ cuda_compiler_version }}  # [linux64 and cuda_compiler_version != "None"]
    - python
    - numpy
    - tbb

test:
  requires:
    - pytest
    - rowan
  imports:
    - hoomd
    - hoomd.md
    - hoomd.hpmc
  commands:
    - pytest --pyargs hoomd -v

about:
  home: https://glotzerlab.engin.umich.edu/hoomd-blue/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'HOOMD-blue is a general-purpose particle simulation toolkit.'

  description: |
    You define particle initial conditions and interactions in a high-level python script. Then tell HOOMD-blue how you want
    to execute the job and it takes care of the rest. Python job scripts give you unlimited flexibility to create custom
    initialization routines, control simulation parameters, and perform in situ analysis.
  doc_url: https://hoomd-blue.readthedocs.io
  dev_url: https://github.com/glotzerlab/hoomd-blue/

extra:
  recipe-maintainers:
    - joaander
    - bdice
